apiVersion: v1
kind: ConfigMap
metadata:
  name: tracker-cracker-config
  namespace: bujo-prod
  labels:
    app: tracker-cracker
data:
  DB_URL: "jdbc:postgresql://postgres.db/bujo"
  DB_DRIVER: "org.postgresql.Driver"
  DB_USER: "bujo_user"
  DB_MAX_POOL: "10"
  APP_PORT: "8080"
  SWAGGER_PORT: "8085"
  SPEC_PATH: "/spec.yaml"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker-cracker
  namespace: bujo-prod
  labels:
    app: tracker_cracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracker_cracker
  template:
    metadata:
      labels:
        app: tracker_cracker
    spec:
      nodeSelector:
        host: self
      containers:
        - name: tracker_cracker
          image: j0rsa/tracker_cracker:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: tracker_cracker-config
            - secretRef:
                name: tracker_cracker-secrets
          ports:
            - containerPort: 8080
            - containerPort: 8085
          resources:
            limits:
              memory: "50Mi"
